# SPDX-License-Identifier: Apache-2.0
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/focal64"
  
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.hostname = "p4"
  config.vm.provision "file", source: "p4-logo.png",   destination: "/home/vagrant/p4-logo.png"
  config.vm.provision "file", source: "p4_16-mode.el", destination: "/home/vagrant/p4_16-mode.el"
  config.vm.provision "file", source: "p4.vim",        destination: "/home/vagrant/p4.vim"

  config.vm.define "dev", autostart: false do |dev|
    dev.vm.provider "virtualbox" do |v|
      v.name = "P4 Tutorial Development" + Time.now.strftime(" %Y-%m-%d")
      v.memory = 2048
      v.cpus = 2
    end
    dev.vm.provision "file", source: "py3localpath.py", destination: "/home/vagrant/py3localpath.py"
    dev.vm.provision "shell", inline: "chmod 755 /home/vagrant/py3localpath.py"
    dev.vm.provision "file", source: "patches/behavioral-model-use-correct-libssl-pkg.patch", destination: "/home/vagrant/patches/behavioral-model-use-correct-libssl-pkg.patch"
    dev.vm.provision "file", source: "patches/mininet-patch-for-2023-jun.patch", destination: "/home/vagrant/patches/mininet-patch-for-2023-jun.patch"
    dev.vm.provision "file", source: "clean.sh", destination: "/home/vagrant/clean.sh"
    dev.vm.provision "shell", inline: "chmod 755 /home/vagrant/clean.sh"
    dev.vm.provision "shell", path: "root-dev-bootstrap.sh"
    dev.vm.provision "shell", path: "root-common-bootstrap.sh"
    dev.vm.provision "shell", privileged: false, path: "user-dev-bootstrap.sh"
    dev.vm.provision "shell", privileged: false, path: "user-common-bootstrap.sh"
  end

  config.vm.define "release", primary: true do |release|
    release.vm.provider "virtualbox" do |v|
      v.name = "P4 Tutorial Release" + Time.now.strftime(" %Y-%m-%d")
      v.memory = 2048
      v.cpus = 2
      v.gui = true
      v.customize ["modifyvm", :id, "--vram", "32"]
    end
    release.vm.provision "file", source: "patches/mininet-patch-for-2023-jun.patch", destination: "/home/vagrant/patches/mininet-patch-for-2023-jun.patch"
    release.vm.provision "shell", path: "root-release-bootstrap.sh"
    release.vm.provision "shell", path: "root-common-bootstrap.sh"
    release.vm.provision "shell", privileged: false, path: "user-common-bootstrap.sh"
  end
end